### ISSUE TITLE
missing fort_update(s)

### ISSUE THREAD

**Issue by dkmur** [UnownHash/Golbat#112]
while playing with fortwatcher I notice missing webhooks for fort_update.
for me, the flow for new forts is often:
1 added
2 edit name+image
3 edit description

Example, added is send(step 1), the name edit (step 2) never received
```
eecf6e240f6831eeae2f165b363ea3a5.16
[20230516 21:08:36] Send added pokestop id: eecf6e240f6831eeae2f165b363ea3a5.16 location: 51.628082,4.926408 fence: Dongen name: "Unknown" time: 1.096 s
[20230516 23:12:24] Send edit pokestop description id: eecf6e240f6831eeae2f165b363ea3a5.16 fence: Dongen name: "Broederpad Links" time: 0.768 s
first_seen_timestamp for eecf6e240f6831eeae2f165b363ea3a5.16 2023-05-16 21:08:34
```

Example, added was never received but I do get an edit name(step2)
```
eec54b8f48d53bb98b008b720a43291e.16
[20230515 21:45:10] noHook edit pokestop name id: eec54b8f48d53bb98b008b720a43291e.16 fence: unfenced name: "Fietsroutenetwerk Drechtsteden" oldname: "Unknown" time: 0.355 s
[20230515 23:16:04] noHook edit pokestop description id: eec54b8f48d53bb98b008b720a43291e.16 fence: unfenced name: "Fietsroutenetwerk Drechtsteden" time: 0.456 s
first_seen_timestamp for eec54b8f48d53bb98b008b720a43291e.16 2023-05-15 20:50:05
```

**Comment by jfberry** [comment]
I would expect this to be two hooks, not 3.  Are you sure the second hook doesn't have all the updates in? Do you have a log of the hooks?
Poracle will log all webhooks regardless of whether it recognises them or not

**Comment by Fabio1988** [comment]
when I look at the source-code that should not happen, except the comparison itself is wrong @jfberry ?!
https://github.com/UnownHash/Golbat/blob/12d7d7abe4ad2650008dcb75a431cc821d77c8c8/decoder/fort.go#LL143C8-L143C8

**Comment by jfberry** [comment]
Yes, I would expect that since the source for name, url and description is all together that these should all be shown as edited in one go - so without an actual copy of the webhooks sent in sequence there isn't any more that can be done

**Comment by jfberry** [comment]
Now poracle has basic support for this (just need to write a default DTS probably) I may be able to start collecting data myself.

**Comment by dkmur** [comment]
bottom exampe (no added send), hooks received
```
{
  "change_type": "edit",
  "edit_types": [
    "name",
    "image_url"
  ],
  "new": {
    "id": "eec54b8f48d53bb98b008b720a43291e.16",
    "type": "pokestop",
    "name": "Fietsroutenetwerk Drechtsteden",
    "description": null,
    "image_url": "https://lh3.googleusercontent.com/xQkdOzT47qbdQ7aQsf4SngWPIWgZLwqBTGZ42Awt6VFIh-HOo1MpXzU7F92BbnaTVkGxD6RUncwP5cM32NvheqJIBDyqTW8q1x0-5Y5K",
    "location": {
      "lat": 51.761318,
      "lon": 4.636668
    }
  },
  "old": {
    "id": "eec54b8f48d53bb98b008b720a43291e.16",
    "type": "pokestop",
    "name": null,
    "description": null,
    "image_url": null,
    "location": {
      "lat": 51.761318,
      "lon": 4.636668
    }
  }
}
```

lateron description is added
```
{
  "change_type": "edit",
  "edit_types": [
    "description"
  ],
  "new": {
    "id": "eec54b8f48d53bb98b008b720a43291e.16",
    "type": "pokestop",
    "name": "Fietsroutenetwerk Drechtsteden",
    "description": "bewegwijzering naar 85",
    "image_url": "https://lh3.googleusercontent.com/xQkdOzT47qbdQ7aQsf4SngWPIWgZLwqBTGZ42Awt6VFIh-HOo1MpXzU7F92BbnaTVkGxD6RUncwP5cM32NvheqJIBDyqTW8q1x0-5Y5K",
    "location": {
      "lat": 51.761318,
      "lon": 4.636668
    }
  },
  "old": {
    "id": "eec54b8f48d53bb98b008b720a43291e.16",
    "type": "pokestop",
    "name": "Fietsroutenetwerk Drechtsteden",
    "description": null,
    "image_url": "https://lh3.googleusercontent.com/xQkdOzT47qbdQ7aQsf4SngWPIWgZLwqBTGZ42Awt6VFIh-HOo1MpXzU7F92BbnaTVkGxD6RUncwP5cM32NvheqJIBDyqTW8q1x0-5Y5K",
    "location": {
      "lat": 51.761318,
      "lon": 4.636668
    }
  }
}
```

**Comment by dkmur** [comment]
> I would expect this to be two hooks, not 3. Are you sure the second hook doesn't have all the updates in? Do you have a log of the hooks? Poracle will log all webhooks regardless of whether it recognises them or not

3 hooks is pretty common

**Comment by jfberry** [comment]
Do you have anything else updating your pokestop db?

**Comment by jfberry** [comment]
The edit without description would be triggered by receiving the result of GetMapForts; the description would then be added by a pokestop being 'opened' when nearby. So that makes sense why you would get three.
The updates could happen quickly and could arrive in the same second (and therefore same webhook dump), would these be logged by whatever you are using?
If you turn on poracle webhook logging then you can grep them out of that also (and we could see the other pokestop events pushed off)
Checking the code visually - it seems ok

**Comment by dkmur** [comment]
> Do you have anything else updating your pokestop db?

can't see what would be doing that, have 2 instances pointing to golbat, one for mon scan and one for forts only on a bigger area

**Comment by dkmur** [comment]
> The edit without description would be triggered by receiving the result of GetMapForts; the description would then be added by a pokestop being 'opened' when nearby. So that makes sense why you would get three. The updates could happen quickly and could arrive in the same second (and therefore same webhook dump), would these be logged by whatever you are using? If you turn on poracle webhook logging then you can grep them out of that also (and we could see the other pokestop events pushed off) Checking the code visually - it seems ok

As this al started with fault finding on deletes I created a simple ncat receiver
<https://github.com/dkmur/fortWatcher/blob/7bfc5aef842b40b3f2a71c56797678e3a1857ed8/fortwatcher.sh#L402>
It should log every hook received when write_raw is enabled. Unless there is an jq error which seems to happen sometimes which might be caused by a double quote in name or description (unreleated to this issue imo, did not check in detail but wonder if golbat is escaping them)

**Comment by jfberry** [comment]
> As this al started with fault finding on deletes I created a simple ncat receiver https://github.com/dkmur/fortWatcher/blob/7bfc5aef842b40b3f2a71c56797678e3a1857ed8/fortwatcher.sh#L402 It should log every hook received when write_raw is enabled. Unless there is an jq error which seems to happen sometimes which might be caused by a double quote in name or description (unreleated to this issue imo, did not check in detail but wonder if golbat is escaping them)

Really need the complete sequence of entries, and alongside the other pokestop webhooks that would be fired at the same time to be able to trace.  BTW, of course quotes would be escaped or they wouldn't be valid json.  If it is poracle logs then thats fine, but otherwise the complete packet to see if the same fort is sent twice in a single packet (which is quite possible here) is occuring and your processor may be picking just the first one

**Comment by jfberry** [comment]
...and looking at the code I am not sure that ncat will be running all the time, so could golbat be attempting to send when the port is closed? (it does not retry). Do you have any connection failures in your golbat log to this receiver?

**Comment by dkmur** [comment]
it should be fast enough as golbat only sends once per second. No connection failures in pm2 error log. Added tee to write the real raw input as well. More info tomorrow when new reports come in

**Comment by jfberry** [comment]
It won't be in the error log, just the general golbat log. Your timings above are >1s; anyway just a "possible" idea.
I suggest turning on webhook logging in your poracle so that you get a complete log (it even logs webhooks it doesn't understand) to compare and eliminate the possibility of missed encounters - since the way your loop works this is certainly a possibility.
In the meantime, since poracle now supports these updates I will create a simple DTS to test it on my system, which is the only part of my dev that I need to do.

**Comment by dkmur** [comment]
pretty sure golbat is fine (will check again in a few days), convinced Im still an idiot, closing the issue.

**Comment by jfberry** [comment]
You can verify easily enough by looking in poracle logs as I suggested
