### ISSUE TITLE
Update hook for naming convention?

### ISSUE THREAD

**Issue by Fabio1988** [UnownHash/Golbat#137]
https://github.com/UnownHash/Golbat/blob/7ecc566fe96b55cfa259f7ea3ab7f65c937efc1d/webhooks/collector.go#L33

Should we add a new hook type for incident? Invasion is only rockets..

Or should we rename and align with poracle?

**Comment by jfberry** [comment]
It probably doesn't matter what the hook is called; everything is expecting it to be called 'invasion' even though it is broader than that now
