### ISSUE TITLE
Auto-remove community ambassadors fort

### ISSUE THREAD

**Issue by ColBreakZ19** [UnownHash/Golbat#174]
Hi !

It is now possible for community ambassadors to creates Pokestop for an event appointment.
The stop only shows before and during the campfire event. It looks like the all have "1639151994" as partner_id. 

=> Can golbat remove them after a day of not being seen with that specific partner_id ?

**Comment by Fabio1988** [comment]
Golbat should soft-delete them if not seen in GMO for some time, checked db row?

**Comment by ColBreakZ19** [comment]
I've checked, still on db & reactmap after +30 days :/
(Seen with Jabes in DMs)

**Comment by jfberry** [comment]
You implied this is because you don’t have fort cleanup turned on

**Comment by Fabio1988** [comment]
> I've checked, still on db & reactmap after +30 days :/ (Seen with Jabes in DMs)

You revisited that cell? It will only be cleaned if last time seen is more than an hour ago and you need to see that GMO frequently

**Comment by ColBreakZ19** [comment]
I deleted one Ambassador stop 1h ago, and It is now again on my map with last seen = 34 Days..

I'll make a test with trafficlight rn, and follow you up my answers !

**Comment by Fabio1988** [comment]
This could mean that gmo proto always contains that fort and client might disable it... Pls post the trafficlight proto

**Comment by ColBreakZ19** [comment]
I can't reproduce the issue, I guess I messed up from the begining...
