### ISSUE TITLE
Issues with Shiny Stats in DB

### ISSUE THREAD

**Issue by Fabio1988** [UnownHash/Golbat#201]
Most of our stats are de-duped by ID of pokemon, like pokemon_stats and pokemon_iv_stats

But with shiny stats we de-dupe by account+ID, as the same pokemon can be seen by multiple accounts and shiny depends on account

Therefore stats like hundo and shundo can't be compared
Therefore calculating the real shiny odds from DB is impossible, because pokemon_iv_stats total is different from shiny total (because of account+ID de-dupe)

We might need to come up with a valid solution, to make the stats better.

One possible solution might be to add a new column to `pokemon_shiny_stats` to reflect the total... Or we simply stop de-duping by account+ID and we only count the shiny of first account encountering. With the latter the behavior would be identical over all stats.

**Comment by jfberry** [comment]
The shiny stats needs to be all encounters from all accounts (and know the account) as shiny are per account.
The other stats should be per pokemon.
If the total isn't in pokemon_shiny_stats it should be (I thought it was when I talked through this with @comstud ), as you are right you can't use the iv stats as the denominator

**Comment by comstud** [comment]
Shiny stats do look at all encounters from all accounts (only counting each account once per encounter id).

But, there is no non-shiny version of the same thing (or a total) in the DB (there is for prometheus). In the PR I did, I avoided any DB migrations. So, yeah, there is currently no way to use the DB compute odds/%.

I think the easiest solution and the one that may make the most sense is to just add a 'total' column to the 'pokemon_shiny_stats' table. I can fix this real easily.

**Comment by comstud** [comment]
Hm. Given all of those stats tables have the same schema at the moment, I'm wondering if it would be better to add a new table with the totals.... which could then also have the same schema. But that feels a little strange to me.

I wouldn't think adding a new column would break blissey...  And whatever is trying to compute shiny odds could just be adjusted to look @ sum(count)/sum(total) or whatever. But maybe @dkmur has opinions.

**Comment by comstud** [comment]
I dunno, what do you think about this:

https://github.com/UnownHash/Golbat/pull/202

**Comment by dkmur** [comment]
> Hm. Given all of those stats tables have the same schema at the moment, I'm wondering if it would be better to add a new table with the totals.... which could then also have the same schema. But that feels a little strange to me.
> 
> I wouldn't think adding a new column would break blissey... And whatever is trying to compute shiny odds could just be adjusted to look @ sum(count)/sum(total) or whatever. But maybe @dkmur has opinions.

Blissey doesnt use any of the "rdm stats tables" of Golbat, just pokemon_area_stats, so no preference from that perspective

**Comment by jfberry** [comment]
> Hm. Given all of those stats tables have the same schema at the moment, I'm wondering if it would be better to add a new table with the totals.... which could then also have the same schema. But that feels a little strange to me.
> 
> I wouldn't think adding a new column would break blissey... And whatever is trying to compute shiny odds could just be adjusted to look @ sum(count)/sum(total) or whatever. But maybe @dkmur has opinions.

The total is unlike any other total - it is total encounters; so it makes sense to keep it with the numerator
