### ISSUE TITLE
More complete ShowcaseRankings

### ISSUE THREAD

**Issue by Mygod** [UnownHash/Golbat#213]
Today after I put my shiny Kyogre in a showcase, I was furious to find out that Golbat (and therefore RM) does not support parsing whether an entered Pokemon was shiny. Therefore, I propose the following additions:

1. Shiny (boolean)
2. Temp evolution (mega can be in fact entered in this showcase)
3. Alignment (shadow/purified/normal)
4. Badge (best buddy/none)

Thoughts?

**Comment by Mygod** [comment]
Maybe also location card? I'm not sure if this is displayed in the showcase since I have no Pokemon with a location card.

**Comment by jfberry** [comment]
I thought reactmap only showed the top 3 scores and not any details about the Pokemon?
I’m ambivalent to whether more detail should be gathered about the individual Pokemon but it’s not especially relevant to your choice of whether to enter a contest or not

**Comment by notheowner** [comment]
> Right it's not, but it's for flexing when other people click on the stop in ReactMap. kek

Flex factor is the best factor. 😔
