### ISSUE TITLE
Stats should populate world everytime

### ISSUE THREAD

**Issue by lenisko** [UnownHash/Golbat#228]
`world` should be populated every time, even when we have correct area. This way we'll get correct global stats.

**Comment by jfberry** [comment]
I kind of agree. At the moment world is unmatched (which probably has a place also) but I chose the name in an unfortunate way. 
this is a breaking change though

**Comment by lenisko** [comment]
we can have one more then `unmatched` that would work as world do now. in normal terms it would be scout outside supported zones

**Comment by jfberry** [comment]
Yes agreed, world should always be added, unmatched should replace current world. would accept pr
