### ISSUE TITLE
Reencounter controller?

### ISSUE THREAD

**Issue by Mygod** [UnownHash/Golbat#246]
Given the encounter limit, is it feasible to have Dragonite ask Golbat for a list of Pokemon that should be reencountered to increase efficiency? (I feel like this should be quick since all the Pokemon is in memory.) If so, what should the API be?

**Comment by jfberry** [comment]
It’s probably not feasible to ask but it would be feasible to change the ruleset. 
Currently re-encounter is on weather change, or Pokemon id change (plus your extra ditto rule)

**Comment by jfberry** [comment]
(Actually I think the rule is when it goes from boosted to non boosted rather than any weather change - but it would certainly be good to codify it to exactly useful re-encounters)

**Comment by jfberry** [comment]
Can you give an example of a category of encounters that are currently repeated that could be avoided?
It may be easier to exemplify so we can see if the dragonite ruleset can reasonably be expanded in a worthwhile way

**Comment by Mygod** [comment]
Guess it's not worth the trouble.
