### ISSUE TITLE
Implement RDM style cell checking

### ISSUE THREAD

**Issue by jfberry** [UnownHash/Golbat#30]
1. Implement RDM-style cell checking where golbat will notice if forts removed.
2. Ensure there is a pokestop / gym webhook sent to indicate a fort is removed

**Comment by jfberry** [comment]
#44 implements

**Comment by Fabio1988** [comment]
Second point not yet. We need a webhook format for that. But I would prefer another PR for that?!

**Comment by Fabio1988** [comment]
#48 follow up ticket
