### ISSUE TITLE
We need to clear pokestop cache before transition?

### ISSUE THREAD

**Issue by Fabio1988** [UnownHash/Golbat#42]
https://github.com/UnownHash/Golbat/blob/cd93a82fd0f7a8bbddc8c6e4327b96a961c47e66/stats.go#L237

if pokestop transitioned to gym this cache entry should expire if not raw processed anymore, so imo we could keep the whole cache in that case?! :)

**Comment by jfberry** [comment]
Agreed, I did cut this out but it's crept back in with a merge

**Comment by Fabio1988** [comment]
I remembered that too, was confused now 🤣

**Comment by Fabio1988** [comment]
[65760482d380bc6464e291a00f67a219f4b0b96a](https://github.com/UnownHash/Golbat/commit/65760482d380bc6464e291a00f67a219f4b0b96a)
