### ISSUE TITLE
Define webhook for cleared/new forts

### ISSUE THREAD

**Issue by Fabio1988** [UnownHash/Golbat#48]
We should define them somehow :)

**Comment by ccev** [comment]
there should be 3 different types:

- edit
- new
- removal

there should be a Fort object:

- type: pokestop | gym 
- name: str
- description: str
- image_url: str
- lat/lon: float/float

Edit data should have:

- edit_type: type | name | description | image_url | location
- old: Fort
- new: Fort

New + Removal data should have:

- fort: Fort

**Comment by ccev** [comment]
there should be 3 different types:

- fort_edit
- fort_new
- fort_removal

there should be a Fort object:

- type: pokestop | gym  (extensible by 3rd parties)
- name: str
- description: str
- image_url: str
- location: { lat: float, lon: float }

Edit data should have:

- edit_type: type | name | description | image_url | location
- old: Fort
- new: Fort

New + Removal data should have:

- fort: Fort

**Comment by Fabio1988** [comment]
```
if change_type = new: ... should be `new: Fort`
if change_type = removal: ... should be `old: Fort`
if change_type = edit: ... should be `old: Fort, new: Fort`
```
