### ISSUE TITLE
cut location floating number with 6 decimals

### ISSUE THREAD

**Issue by Fabio1988** [UnownHash/Golbat#77]
`-36.84929156444202,174.76839760477938`
That's too accurate, we should cut them on pokemon

**Comment by lenisko** [comment]
Leaving as addition

![image](https://rapidlasso.files.wordpress.com/2019/05/longitude_latitude_required_digits.png)

**Comment by Mygod** [comment]
Are there any advantage in cutting it at all? Since it is a float64 in the proto, I think that we should keep raw data as is and not touch it.

(By the way, capture probabilities are float32 in proto.)

**Comment by lenisko** [comment]
@Mygod storage & lack of need for precission above 6 digits

**Comment by jfberry** [comment]
Floats are either 32 or 64 bit - no of decimal points makes no difference to storage size

**Comment by lenisko** [comment]
Yes, but we use 64-bit floats which are meaningless, nope? 32 should be good enough for most needs.

**Comment by Mygod** [comment]
Well you are only saving 8 bytes per row but losing scanned information (server gives you float64). I don't think it's worth this tiny optimization.

**Comment by lenisko** [comment]
The main "problem" I saw was at the front side. When data was sent to users (maps/notifications). But that's application role to round values and not a scanner.

**Comment by Fabio1988** [comment]
Yeah I am fine to keep it like that. If it's really only 8 bytes per row to save, that would be 4 MB for 500k Pokemon processing per hour. and as Golbat supports now pokemon processing in memory only as well I am fine with keeping the high precision right now :) 

If any other thoughts - Feel free to reopen or create a new issue :)
