### ISSUE TITLE
Invasion Teams & Giovanni detection

### ISSUE THREAD

**Issue by ccev** [UnownHash/Golbat#80]
I would like to discuss how to process invasion teams & confirmed Giovanni

Refer to #12 for real invasion data examples.

# Giovanni

## Raw Data

This data is best extracted from a `StartIncidentOutProto`.

`StartIncidentOutProto.Incident.step` is an array of `ClientIncidentStepProto`. In it, the confirmed grunt character is in both `pokestop_dialogue.dialogue_line.character` (`ClientPokestopNpcDialogueStepProto`) and `invasion_battle.character` (`ClientInvasionBattleStepProto`)

A confirmed Giovanni is type `44`. Male Decoy is `45` and Female Decoy is `46` (used by the game). Note that "unconfirmed" Giovanni is also `44`

## Processing

- Add a new bool column to the `incident` table. I suggest calling it `character_confirmed`
- After processing this, send a new webhook. This can then also have the same `character_confirmed` bool field.

## Notes

- There's a relatively fresh `_u` flag for grunt UICONs. This is part of the standard but afaik, no uicon repo supports it. Reference PR: Uicons/UIcons#34

# Teams

## Raw Data

This data is provided in a `OpenInvasionCombatSessionOutProto`.

`OpenInvasionCombatSessionOutProto.combat.opponent.active_pokemon` is the first slot, OpenInvasionCombatSessionOutProto.combat.opponent.reserve_pokemon is an array containing the second and third slot (in order).

These Pokemon are of type `CombatPokemonProto`. Refer to #12 for details on this. 

You may want to abort processing if the array size != 2. This should never happen. Also only process OpenInvasionCombatSessionOutProtos that have teh SUCCESS status. It's not uncommon these can fail.

## Processing

I'm not sure how to best tackle this.

### Pokemon Data

- Useful: Pokedex ID and Form Id
- Possibly useful: Gender (not sure if same across players)
- Possibly useful: Moves (not sure if same across players), possibly interesting for hardcore players, but most likely not worth storing
- Likely useless: CP/CPM/IVs. Most likely different across players

### Storing

- If we only decide to store pokedexId and formId, we would get away with adding 6 new columns to the `incidents` table: `slot_x_pokemon_id` and `slot_x_form` where x is 0, 1, 2 (or 1, 2, 3)
- If we decide to store more, we would probably have to make a new table. This will become quite unperformant and kind of ugly
- When a team is detected, send out a incident webhook with a field that should look like this:

```js
team: [
    {
        "pokemon_id": 0,
        "form": 0,
        ...
    },
    ...
]
```

**Comment by jfberry** [comment]
I agree. All for this but just to say that even if storing moves you can add more columns to invasion without worrying. A wide nullable columns here are probably better than a sub-table for easy speed of updating IMO

**Comment by TurtIeSocks** [comment]
Onboard with only starting with `pokemon_id` and `form_id`. I don't currently have it on my radar to add filtering for specific mons but I'm sure I'll be suckered into it at some point once the MITMs start supporting it. 

Agree with the boolean confirmed column.

**Comment by TurtIeSocks** [comment]
After starting work on this last night I'm already over the long column names. Can we just use `pokemon_1`, `form_1`?
